$font = JetBrains Mono Nerd Font

general {
    hide_cursor = true 
}

animations {
    enabled = true

    bezier = linear, 1, 1, 0, 0
    bezier = inLockScreen, 0.83, 0, 0.17, 1  
    bezier = outLockScreen, 0.09, 0.02, 0.49, 1.01

    animation = fadeIn,           1, 5,   inLockScreen 
    animation = fadeOut,          1, 5,   outLockScreen 
    animation = inputFieldDots,   1, 2,   linear
}

background {
    monitor =
    path = ~/Imágenes/Wallpapers/gruvbox_astro.jpg
    blur_passes = 3
}

input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(fabd2fee) 45deg
    check_color = rgba(fe8019ee) rgba(d65d0eee) 120deg
    fail_color = rgba(cc241dee) rgba(cc241dee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 12

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL
    dots_size = 0.3
    dots_spacing = 0.3

    position = 20, -420
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 30, -70
    halign = center 
    valign = top 
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = 30, -100
    halign = center
    valign = top
}

image {
    monitor = 
    path = ~/Imágenes/profilePics/proflie.jpg
    border_color = rgba(83a598ee)
    border_size = 3
    rounding = -1

    position = 30, -150
    halign = center
    valing = top
}
