##############################
### WINDOWS AND WORKSPACES ###
##############################

#Layer rules
layerrule = blur on, match:class swaync-control-center
layerrule = blur on, match:class swaync-notification-window
#layerrule = ignorezero, match:class swaync-control-center
#layerrule = ignore_zero, match:class swaync-notification-window
layerrule = ignore_alpha 0.5, match:class swaync-control-center
layerrule = ignore_alpha 0.5, match:class swaync-notification-window

# Example windowrule
windowrule = match:class kitty, opacity 0.95 0.90
windowrule = match:class waypaper, float on
windowrule = match:class org.gnome.Nautilus, float on 

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

