$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$firefox = firefox
$wallpaper = waypaper
$screenshot = hyprshot -m window -o ~/Imágenes/screenshots
$regionScreen = hyprshot -m region -o ~/Imágenes/screenshots
